---
- name: Deploy Flask app (simple, no requirements.txt)
  hosts: group_a
  become: yes
  vars:
    app_user: flaskapp
    app_dir: /opt/flaskapp
    repo_url: "https://github.com/raz-sarusi/flaskproject.git"
    app_module: "flask_project:app"
    listen_port: 8000

    discord_webhook_url: ""

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install system packages
      apt:
        name:
          - git
          - python3
          - python3-venv
          - python3-pip
        state: present

    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        create_home: no
        shell: /usr/sbin/nologin

    - name: Create app directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"
      loop:
        - "{{ app_dir }}"
        - "{{ app_dir }}/app"
        - "{{ app_dir }}/venv"

    - name: Clone application repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}/app"
        version: "main"
        force: yes
      become_user: "{{ app_user }}"

    - name: Create virtualenv
      command: "python3 -m venv {{ app_dir }}/venv"
      args:
        creates: "{{ app_dir }}/venv/bin/activate"
      become_user: "{{ app_user }}"

    - name: Install needed Python packages without requirements.txt
      command: "{{ app_dir }}/venv/bin/pip install --upgrade pip Flask requests gunicorn"
      become_user: "{{ app_user }}"

    - name: Ensure SQLite file is writable by app user
      file:
        path: "{{ app_dir }}/app/messages.db"
        state: file
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0644"
      ignore_errors: yes

    - name: Deploy systemd service unit
      template:
        src: "templates/flaskapp.service.j2"
        dest: "/etc/systemd/system/flaskapp.service"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Enable & start flaskapp service
      systemd:
        name: flaskapp
        state: started
        enabled: yes

    - name: Allow listening port in UFW if exists
      command: "ufw allow {{ listen_port }}/tcp"
      ignore_errors: yes

    - name: Debug URL to test
      debug:
        msg: "Browse http://{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ listen_port }}/"
